# Generated by Django 5.2 on 2025-04-26 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blockheight", models.IntegerField()),
                ("blockheaderhash", models.CharField(unique=True)),
                ("version", models.IntegerField()),
                ("prev_blockheaderhash", models.CharField()),
                ("merkle_root", models.CharField()),
                ("time", models.IntegerField()),
                ("bits", models.CharField()),
                ("nonce", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ContextRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("html", models.TextField(max_length=1000000)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prev_revision",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pages.contextrevision",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CoinbaseScriptsig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scriptsig", models.BinaryField()),
                ("scriptsig_text", models.CharField(null=True)),
                (
                    "context_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.contextrevision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(null=True)),
                ("hash", models.BinaryField(unique=True)),
                ("content_type", models.CharField()),
                ("content_size", models.IntegerField()),
                ("filename", models.CharField(null=True, unique=True)),
                ("text", models.TextField(default="")),
                ("json", models.JSONField(default=dict)),
                (
                    "context_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.contextrevision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scriptpubkey", models.BinaryField()),
                ("scriptpubkey_text", models.CharField()),
                (
                    "context_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.contextrevision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash", models.BinaryField(unique=True)),
                ("mime_type", models.CharField()),
                ("size", models.IntegerField()),
                ("params", models.JSONField()),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.block"
                    ),
                ),
                (
                    "coinbase_scriptsig",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.coinbasescriptsig",
                    ),
                ),
                (
                    "context_revision",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.contextrevision",
                    ),
                ),
                (
                    "inscription",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.inscription",
                    ),
                ),
                (
                    "op_return",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.opreturn",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tx",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("n", models.IntegerField()),
                ("txid", models.CharField()),
                ("wtxid", models.CharField()),
                ("version", models.IntegerField()),
                ("locktime", models.IntegerField()),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.block"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TxIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("n", models.IntegerField()),
                ("txid", models.CharField()),
                ("vout", models.BigIntegerField()),
                ("sequence", models.BigIntegerField()),
                (
                    "tx",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.tx"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="inscription",
            name="txin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pages.txin"
            ),
        ),
        migrations.AddField(
            model_name="coinbasescriptsig",
            name="txin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pages.txin"
            ),
        ),
        migrations.CreateModel(
            name="TxOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("n", models.IntegerField()),
                ("value", models.BigIntegerField()),
                (
                    "tx",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.tx"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="opreturn",
            name="txout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pages.txout"
            ),
        ),
    ]
