# Generated by Django 5.2 on 2025-04-12 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                ("blockheight", models.IntegerField(primary_key=True, serialize=False)),
                ("blockheaderhash", models.CharField(unique=True)),
                ("version", models.IntegerField()),
                ("prev_blockheaderhash", models.CharField()),
                ("merkle_root", models.CharField()),
                ("time", models.IntegerField()),
                ("bits", models.CharField()),
                ("nonce", models.BigIntegerField()),
                ("coinbase_tx_scriptsig", models.CharField(max_length=200)),
                ("coinbase_tx_scriptsig_text", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="OpReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.CharField(max_length=160)),
                ("text", models.CharField(max_length=80)),
                ("txout_n", models.IntegerField()),
                ("txout_value", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("context", models.TextField()),
                (
                    "block",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.block",
                    ),
                ),
                (
                    "op_return",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.opreturn",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tx",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("txid", models.CharField()),
                ("wtxid", models.CharField()),
                ("version", models.IntegerField()),
                ("locktime", models.IntegerField()),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.block"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="opreturn",
            name="tx",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pages.tx"
            ),
        ),
    ]
