# Generated by Django 5.2 on 2025-04-20 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContextRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prev_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pages.contextrevision",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blockheight", models.IntegerField()),
                ("blockheaderhash", models.CharField(unique=True)),
                ("version", models.IntegerField()),
                ("prev_blockheaderhash", models.CharField()),
                ("merkle_root", models.CharField()),
                ("time", models.IntegerField()),
                ("bits", models.CharField()),
                ("nonce", models.BigIntegerField()),
                (
                    "context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.contextrevision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tx",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("n", models.IntegerField()),
                ("txid", models.CharField()),
                ("wtxid", models.CharField()),
                ("version", models.IntegerField()),
                ("locktime", models.IntegerField()),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.block"
                    ),
                ),
                (
                    "context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.contextrevision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TxIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("n", models.IntegerField()),
                ("txid", models.CharField()),
                ("vout", models.BigIntegerField()),
                ("scriptsig_text", models.CharField(null=True)),
                ("sequence", models.BigIntegerField()),
                (
                    "context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.contextrevision",
                    ),
                ),
                (
                    "tx",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.tx"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(null=True)),
                ("content_type", models.CharField()),
                ("content_size", models.IntegerField()),
                ("filename", models.CharField(null=True)),
                ("text", models.TextField(null=True)),
                (
                    "context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.contextrevision",
                    ),
                ),
                (
                    "txin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.txin"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TxOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("n", models.IntegerField()),
                ("scriptpubkey", models.BinaryField(null=True)),
                ("scriptpubkey_text", models.CharField(null=True)),
                ("value", models.BigIntegerField()),
                (
                    "context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.contextrevision",
                    ),
                ),
                (
                    "tx",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.tx"
                    ),
                ),
            ],
        ),
    ]
