# Generated by Django 5.2 on 2025-05-05 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="mime_type",
            field=models.CharField(db_index=True),
        ),
        migrations.AlterField(
            model_name="inscription",
            name="content_hash",
            field=models.BinaryField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="inscription",
            name="filename",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="inscription",
            name="mime_subtype",
            field=models.CharField(db_index=True),
        ),
        migrations.AlterField(
            model_name="inscription",
            name="mime_type",
            field=models.CharField(db_index=True),
        ),
    ]
