# Generated by Django 5.2 on 2025-04-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="txin",
            name="scriptsig_text",
            field=models.CharField(null=True),
        ),
    ]
