# Generated by Django 5.2 on 2025-04-23 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="block",
            old_name="context",
            new_name="context_revision",
        ),
        migrations.RenameField(
            model_name="contextrevision",
            old_name="text",
            new_name="html",
        ),
        migrations.RenameField(
            model_name="inscription",
            old_name="context",
            new_name="context_revision",
        ),
        migrations.RenameField(
            model_name="tx",
            old_name="context",
            new_name="context_revision",
        ),
        migrations.RenameField(
            model_name="txin",
            old_name="context",
            new_name="context_revision",
        ),
        migrations.RenameField(
            model_name="txout",
            old_name="context",
            new_name="context_revision",
        ),
    ]
