# Generated by Django 5.2 on 2025-04-11 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("context", models.TextField()),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.block"
                    ),
                ),
                (
                    "op_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.opreturn"
                    ),
                ),
            ],
        ),
    ]
