# Generated by Django 5.2 on 2025-05-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_alter_content_mime_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="block_time",
            field=models.BigIntegerField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="content",
            name="text",
            field=models.TextField(db_index=True, default=""),
        ),
    ]
