# Generated by Django 5.2 on 2025-04-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_alter_txin_scriptsig_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscription",
            name="number",
            field=models.IntegerField(null=True),
        ),
    ]
