# Generated by Django 5.2 on 2025-04-11 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="block",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="pages.block"
            ),
        ),
        migrations.AlterField(
            model_name="content",
            name="op_return",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pages.opreturn",
            ),
        ),
    ]
