# Generated by Django 5.2 on 2025-05-11 08:48

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_alter_content_block_time_alter_content_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="content",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="pages_conte_search__52b9d3_gin"
            ),
        ),
        # Generated by Claude 3.7
        # Populate the search_vector field for existing records
        migrations.RunSQL(
            sql="""
            UPDATE pages_content
            SET search_vector = to_tsvector('english', COALESCE(text, ''))
            """,
            reverse_sql="UPDATE pages_content SET search_vector = NULL",
        ),
        # Create a function to update the search vector
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION pages_content_search_vector_update() RETURNS trigger AS $$
            BEGIN
                NEW.search_vector := to_tsvector('english', COALESCE(NEW.text, ''));
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """,
            reverse_sql="DROP FUNCTION IF EXISTS pages_content_search_vector_update()",
        ),
        # Create a trigger to automatically update the search vector
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER pages_content_search_vector_update
            BEFORE INSERT OR UPDATE OF text
            ON pages_content
            FOR EACH ROW
            EXECUTE FUNCTION pages_content_search_vector_update();
            """,
            reverse_sql="DROP TRIGGER IF EXISTS pages_content_search_vector_update ON pages_content",
        ),
    ]
