# Generated by Django 5.2 on 2025-05-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_content_search_vector_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="block_height",
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="content",
            name="is_brc20",
            field=models.BooleanField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="content",
            name="mime_subtype",
            field=models.CharField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="content",
            name="block_time",
            field=models.BigIntegerField(db_index=True),
        ),
    ]
