# Generated by Django 5.2 on 2025-05-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_content_block_height_content_is_brc20_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="content",
            index=models.Index(
                fields=["block_height", "mime_type"], name="content_bh_mime_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(
                fields=["mime_type", "block_height"], name="content_mime_bh_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(
                fields=[
                    "coinbase_scriptsig",
                    "op_return",
                    "inscription",
                    "is_brc20",
                    "block_height",
                ],
                name="content_type_bh_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(
                condition=models.Q(
                    ("coinbase_scriptsig__isnull", True),
                    ("inscription__isnull", False),
                    ("op_return__isnull", True),
                ),
                fields=["block_height", "block_time"],
                name="content_inscriptions_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(
                condition=models.Q(("is_brc20", False)),
                fields=["block_height", "block_time"],
                name="content_not_brc20_idx",
            ),
        ),
    ]
